// <auto-generated />
using API_Test.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Test.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20250422131247_NameChange")]
    partial class NameChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Test.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Allt om kodning",
                            Name = "Programmering"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Allt om spel",
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Allt om matlagning",
                            Name = "Matlagning"
                        });
                });

            modelBuilder.Entity("API_Test.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LinkName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LinkName = "https://github.com"
                        },
                        new
                        {
                            Id = 2,
                            LinkName = "https://stackoverflow.com"
                        },
                        new
                        {
                            Id = 3,
                            LinkName = "https://www.gamereactor.com"
                        },
                        new
                        {
                            Id = 4,
                            LinkName = "https://www.fz.se"
                        },
                        new
                        {
                            Id = 5,
                            LinkName = "https://www.recept.se"
                        },
                        new
                        {
                            Id = 6,
                            LinkName = "https://www.koket.se"
                        },
                        new
                        {
                            Id = 7,
                            LinkName = "https://www.matklubben.se"
                        });
                });

            modelBuilder.Entity("API_Test.Models.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "0731234567"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Jane",
                            LastName = "Smith",
                            Phone = "0732345678"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Phone = "0733456789"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Bob",
                            LastName = "Brown",
                            Phone = "0734567890"
                        });
                });

            modelBuilder.Entity("InterestLink", b =>
                {
                    b.Property<int>("InterestsId")
                        .HasColumnType("int");

                    b.Property<int>("LinksId")
                        .HasColumnType("int");

                    b.HasKey("InterestsId", "LinksId");

                    b.HasIndex("LinksId");

                    b.ToTable("InterestLink");

                    b.HasData(
                        new
                        {
                            InterestsId = 1,
                            LinksId = 1
                        },
                        new
                        {
                            InterestsId = 1,
                            LinksId = 2
                        },
                        new
                        {
                            InterestsId = 2,
                            LinksId = 3
                        },
                        new
                        {
                            InterestsId = 2,
                            LinksId = 4
                        },
                        new
                        {
                            InterestsId = 3,
                            LinksId = 5
                        },
                        new
                        {
                            InterestsId = 3,
                            LinksId = 6
                        },
                        new
                        {
                            InterestsId = 3,
                            LinksId = 7
                        });
                });

            modelBuilder.Entity("InterestPeople", b =>
                {
                    b.Property<int>("InterestsId")
                        .HasColumnType("int");

                    b.Property<int>("PeopleId")
                        .HasColumnType("int");

                    b.HasKey("InterestsId", "PeopleId");

                    b.HasIndex("PeopleId");

                    b.ToTable("InterestPeople");

                    b.HasData(
                        new
                        {
                            InterestsId = 2,
                            PeopleId = 1
                        },
                        new
                        {
                            InterestsId = 1,
                            PeopleId = 2
                        },
                        new
                        {
                            InterestsId = 3,
                            PeopleId = 2
                        },
                        new
                        {
                            InterestsId = 2,
                            PeopleId = 3
                        },
                        new
                        {
                            InterestsId = 3,
                            PeopleId = 3
                        },
                        new
                        {
                            InterestsId = 1,
                            PeopleId = 4
                        },
                        new
                        {
                            InterestsId = 2,
                            PeopleId = 4
                        },
                        new
                        {
                            InterestsId = 3,
                            PeopleId = 4
                        });
                });

            modelBuilder.Entity("LinkPeople", b =>
                {
                    b.Property<int>("LinksId")
                        .HasColumnType("int");

                    b.Property<int>("PeopleId")
                        .HasColumnType("int");

                    b.HasKey("LinksId", "PeopleId");

                    b.HasIndex("PeopleId");

                    b.ToTable("LinkPeople");

                    b.HasData(
                        new
                        {
                            LinksId = 1,
                            PeopleId = 2
                        },
                        new
                        {
                            LinksId = 1,
                            PeopleId = 4
                        },
                        new
                        {
                            LinksId = 2,
                            PeopleId = 2
                        },
                        new
                        {
                            LinksId = 2,
                            PeopleId = 4
                        },
                        new
                        {
                            LinksId = 3,
                            PeopleId = 1
                        },
                        new
                        {
                            LinksId = 3,
                            PeopleId = 3
                        },
                        new
                        {
                            LinksId = 3,
                            PeopleId = 4
                        },
                        new
                        {
                            LinksId = 4,
                            PeopleId = 1
                        },
                        new
                        {
                            LinksId = 4,
                            PeopleId = 3
                        },
                        new
                        {
                            LinksId = 4,
                            PeopleId = 4
                        },
                        new
                        {
                            LinksId = 5,
                            PeopleId = 2
                        },
                        new
                        {
                            LinksId = 5,
                            PeopleId = 3
                        },
                        new
                        {
                            LinksId = 5,
                            PeopleId = 4
                        },
                        new
                        {
                            LinksId = 6,
                            PeopleId = 2
                        },
                        new
                        {
                            LinksId = 6,
                            PeopleId = 3
                        },
                        new
                        {
                            LinksId = 6,
                            PeopleId = 4
                        },
                        new
                        {
                            LinksId = 7,
                            PeopleId = 2
                        },
                        new
                        {
                            LinksId = 7,
                            PeopleId = 3
                        },
                        new
                        {
                            LinksId = 7,
                            PeopleId = 4
                        });
                });

            modelBuilder.Entity("InterestLink", b =>
                {
                    b.HasOne("API_Test.Models.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Test.Models.Link", null)
                        .WithMany()
                        .HasForeignKey("LinksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterestPeople", b =>
                {
                    b.HasOne("API_Test.Models.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Test.Models.People", null)
                        .WithMany()
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkPeople", b =>
                {
                    b.HasOne("API_Test.Models.Link", null)
                        .WithMany()
                        .HasForeignKey("LinksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Test.Models.People", null)
                        .WithMany()
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
